package calculadora;

import javax.swing.JOptionPane;

/**
 *
 * @author Juan Carlos Quiroz Aguilar
 *
 * Esta clase inicializa los componentes de la intefaz grafica
 */
public class CalculadoraUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraUI
     */
    public CalculadoraUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        op1 = new javax.swing.JTextField();
        op2 = new javax.swing.JTextField();
        btnSumar = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btnMiltiplicacion = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnModulo = new javax.swing.JButton();
        btnPotencia = new javax.swing.JButton();
        btnRaiz = new javax.swing.JButton();
        bntSeno = new javax.swing.JButton();
        btnArcoseno = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnExp = new javax.swing.JButton();
        btnCoseno = new javax.swing.JButton();
        btnTangente = new javax.swing.JButton();
        btnArcocoseno = new javax.swing.JButton();
        btnArcotangente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        res = new javax.swing.JTextField();
        btnlimpiar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(238, 85, 42));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Operando 1");

        jLabel2.setText("Operando 2");

        op1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                op1KeyTyped(evt);
            }
        });

        op2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                op2KeyTyped(evt);
            }
        });

        btnSumar.setBackground(new java.awt.Color(0, 204, 204));
        btnSumar.setForeground(new java.awt.Color(0, 0, 0));
        btnSumar.setText("Suma");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnRestar.setBackground(new java.awt.Color(0, 204, 204));
        btnRestar.setText("Resta");
        btnRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestarActionPerformed(evt);
            }
        });

        btnMiltiplicacion.setBackground(new java.awt.Color(0, 204, 204));
        btnMiltiplicacion.setText("Multiplicacion");
        btnMiltiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiltiplicacionActionPerformed(evt);
            }
        });

        btnDivision.setBackground(new java.awt.Color(0, 204, 204));
        btnDivision.setText("Division");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        btnModulo.setBackground(new java.awt.Color(0, 204, 204));
        btnModulo.setText("Modulo");
        btnModulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModuloActionPerformed(evt);
            }
        });

        btnPotencia.setBackground(new java.awt.Color(0, 204, 204));
        btnPotencia.setText("Potencia");
        btnPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPotenciaActionPerformed(evt);
            }
        });

        btnRaiz.setBackground(new java.awt.Color(0, 204, 204));
        btnRaiz.setText("Raiz");
        btnRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaizActionPerformed(evt);
            }
        });

        bntSeno.setBackground(new java.awt.Color(0, 204, 204));
        bntSeno.setText("Seno");
        bntSeno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSenoActionPerformed(evt);
            }
        });

        btnArcoseno.setBackground(new java.awt.Color(0, 204, 204));
        btnArcoseno.setText("Arcoseno");
        btnArcoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcosenoActionPerformed(evt);
            }
        });

        btnLog.setBackground(new java.awt.Color(0, 204, 204));
        btnLog.setText("Log");
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnExp.setBackground(new java.awt.Color(0, 204, 204));
        btnExp.setText("Exp");
        btnExp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpActionPerformed(evt);
            }
        });

        btnCoseno.setBackground(new java.awt.Color(0, 204, 204));
        btnCoseno.setText("Coseno");
        btnCoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosenoActionPerformed(evt);
            }
        });

        btnTangente.setBackground(new java.awt.Color(0, 204, 204));
        btnTangente.setText("Tangente");
        btnTangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangenteActionPerformed(evt);
            }
        });

        btnArcocoseno.setBackground(new java.awt.Color(0, 204, 204));
        btnArcocoseno.setText("Arcocoseno");
        btnArcocoseno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcocosenoActionPerformed(evt);
            }
        });

        btnArcotangente.setBackground(new java.awt.Color(0, 204, 204));
        btnArcotangente.setText("Arcotangente");
        btnArcotangente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcotangenteActionPerformed(evt);
            }
        });

        jLabel4.setText("Resultado");

        res.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bntSeno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnArcoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnArcocoseno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDivision, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(btnSumar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMiltiplicacion)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnExp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnArcotangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTangente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(op2)
                            .addComponent(op1)
                            .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(op1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(op2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSumar)
                    .addComponent(btnRestar)
                    .addComponent(btnMiltiplicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDivision)
                    .addComponent(btnModulo)
                    .addComponent(btnPotencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExp)
                    .addComponent(btnLog)
                    .addComponent(btnRaiz))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntSeno)
                    .addComponent(btnCoseno)
                    .addComponent(btnTangente))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArcoseno)
                    .addComponent(btnArcocoseno)
                    .addComponent(btnArcotangente))
                .addGap(24, 24, 24))
        );

        btnlimpiar.setBackground(new java.awt.Color(255, 255, 0));
        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        btnsalir.setBackground(new java.awt.Color(255, 0, 51));
        btnsalir.setText("Salir");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Calculadora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnlimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlimpiar)
                    .addComponent(btnsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo se lanza al presionar el boton salir en la UI indicandole al
     * sistema que la aplicacion a finalizado de forma exitosa
     *
     * @param evt
     */
    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnsalirActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton arcoseno en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float, se crea una variable objeto de la clase CCalculo para poder
     * utilizar sus metodos. Accede al metodo Arcocoseno del objeto CCalculo
     * enviandole el valor del campo op1.
     *
     * @param evt
     * @exception Arco, se lanza esta exepcion cuando el valor absoluto del
     * contendio del op1 es mayor a 1.
     */

    private void btnArcocosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcocosenoActionPerformed
        float fop1;
        double fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();

        fop1 = Float.parseFloat(op1.getText());

        try {
            fres = oCalculo.Arcocoseno(fop1);

            res.setText(String.valueOf(fres));
        } catch (Arco | java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnArcocosenoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        op1.setText("");
        op2.setText("");
        res.setText("");
    }//GEN-LAST:event_btnlimpiarActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton suma en la UI toma el valor
     * que tiene la casilla op1 y lo transforma a una variable de tipo float
     * hace lo mismo con el segundo op2, se crea una variable objeto de la clase
     * CCalculo para poder utilizar sus metodos. Accede al metodo suma del
     * objeto CCalculo enviandole el valor del campo op1 y op2
     *
     * @param evt
     */

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        float fop1;
        float fop2;
        float fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();

        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = Float.parseFloat(op2.getText());
            fres = oCalculo.Sumar(fop1, fop2);
            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }

    }//GEN-LAST:event_btnSumarActionPerformed
    /**
     * Este metodo se utiliza al presionar el boton resta en la UI toma el valor
     * que tiene la casilla op1 y lo transforma a una variable de tipo float
     * hace lo mismo con el segundo op2 pero este lo multiplica por -1, para
     * tener una resta, se crea una variable objeto de la clase CCalculo para
     * poder utilizar sus metodos. Accede al metodo suma del objeto CCalculo
     * enviandole el valor del campo op1 y op2
     *
     * @param evt
     */
    private void btnRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestarActionPerformed
        float fop1;
        float fop2;
        float fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();

        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = (Float.parseFloat(op2.getText())) * (-1);

            fres = oCalculo.Sumar(fop1, fop2);

            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnRestarActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton multiplicacion en la UI toma
     * el valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float hace lo mismo con el segundo op2, se crea una variable objeto de la
     * clase CCalculo para poder utilizar sus metodos. Accede al metodo
     * multiplicacion del objeto CCalculo enviandole el valor del campo op1 y
     * op2
     *
     * @param evt
     */

    private void btnMiltiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiltiplicacionActionPerformed
        float fop1;
        float fop2;
        float fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();

        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = Float.parseFloat(op2.getText());
            fres = oCalculo.Multiplicar(fop1, fop2);
            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnMiltiplicacionActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton division en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float hace lo mismo con el segundo op2, se crea una variable objeto de la
     * clase CCalculo para poder utilizar sus metodos. Accede al metodo division
     * del objeto CCalculo enviandole el valor del campo op1 y op2
     *
     * @exception DivCero Esta exepcion se lanza cuando b es igual a cero ya que
     * la division entre cero no esta permitida
     *
     * @param evt
     */

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        float fop1;
        float fop2;
        float fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = Float.parseFloat(op2.getText());
            fres = oCalculo.Dividir(fop1, fop2);
            res.setText(String.valueOf(fres));
        } catch (DivCero e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnDivisionActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton modulo en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float hace lo mismo con el segundo op2, se crea una variable objeto de la
     * clase CCalculo para poder utilizar sus metodos. Accede al metodo modulo
     * del objeto CCalculo enviandole el valor del campo op1 y op2
     *
     * @exception DivCero Esta exepcion se lanza cuando b es igual a cero ya que
     * la division entre cero no esta permitida
     *
     * @param evt
     */

    private void btnModuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModuloActionPerformed
        float fop1;
        float fop2;
        float fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = Float.parseFloat(op2.getText());

            fres = oCalculo.Modulo(fop1, fop2);

            res.setText(String.valueOf(fres));
        } catch (DivCero e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnModuloActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton potencia en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float hace lo mismo con el segundo op2, se crea una variable objeto de la
     * clase CCalculo para poder utilizar sus metodos. Accede al metodo potencia
     * del objeto CCalculo enviandole el valor del campo op1 y op2
     *
     * @param evt
     */

    private void btnPotenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPotenciaActionPerformed
        float fop1;
        float fop2;
        double fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = Float.parseFloat(op2.getText());

            fres = oCalculo.Potencia(fop1, fop2);
            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnPotenciaActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton raiz en la UI toma el valor
     * que tiene la casilla op1 y lo transforma a una variable de tipo float
     * hace lo mismo con el segundo op2, se crea una variable objeto de la clase
     * CCalculo para poder utilizar sus metodos. Accede al metodo raiz del
     * objeto CCalculo enviandole el valor del campo op1 y op2
     *
     * @exception RaizCero Esta exepcion se lanza cuando b es igual a cero ya
     * que la raiz cero no esta permitida
     *
     * @exception Raizpar Esta exepcion se lanza cuando b es numero par y a es
     * un menero menor a 0, ya que las raices pares de numeros negativos no
     * estan definidas en los numeros reales
     *
     * @param evt
     */

    private void btnRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaizActionPerformed
        float fop1;
        float fop2;
        double fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());
            fop2 = Float.parseFloat(op2.getText());

            fres = oCalculo.Raiz(fop1, fop2);
            res.setText(String.valueOf(fres));
        } catch (RaizCero | Raizpar e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnRaizActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton Log en la UI toma el valor
     * que tiene la casilla op1 y lo transforma a una variable de tipo float se
     * crea una variable objeto de la clase CCalculo para poder utilizar sus
     * metodos. Accede al metodo raiz del objeto CCalculo enviandole el valor
     * del campo op1, el valor de op2 es desechado ya que la funcion log solo
     * recibe un parametro
     *
     * @param evt
     *
     * @exception LogCero Esta exepcion se lanza cuando a es menor a cero ya que
     * la funcion Log solo esta definida para numeros mayores o igual a cero
     */

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:

        float fop1;
        double fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());
            fres = oCalculo.Log(fop1);
            op2.setText("");
            res.setText(String.valueOf(fres));

        } catch (LogCero e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnLogActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton Exp en la UI toma el valor
     * que tiene la casilla op1 y lo transforma a una variable de tipo float se
     * crea una variable objeto de la clase CCalculo para poder utilizar sus
     * metodos. Accede al metodo Exp del objeto CCalculo enviandole el valor del
     * campo op1, el valor de op2 es desechado ya que la funcion exp solo recibe
     * un parametro
     *
     * @param evt
     */

    private void btnExpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpActionPerformed
        float fop1;
        double fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();

        try {
            fop1 = Float.parseFloat(op1.getText());

            fres = oCalculo.Exp(fop1);
            op2.setText("");

            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnExpActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton seno en la UI toma el valor
     * que tiene la casilla op1 y lo transforma a una variable de tipo float se
     * crea una variable objeto de la clase CCalculo para poder utilizar sus
     * metodos. Accede al metodo Exp del objeto CCalculo enviandole el valor del
     * campo op1, el valor de op2 es desechado ya que la funcion seno solo
     * recibe un parametro
     *
     * @param evt
     */

    private void bntSenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSenoActionPerformed
        float fop1;
        double fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());

            fres = oCalculo.Seno(fop1);
            op2.setText("");

            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_bntSenoActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton coseno en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float se crea una variable objeto de la clase CCalculo para poder
     * utilizar sus metodos. Accede al metodo Exp del objeto CCalculo enviandole
     * el valor del campo op1, el valor de op2 es desechado ya que la funcion
     * coseno solo recibe un parametro
     *
     * @param evt
     */

    private void btnCosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosenoActionPerformed
        float fop1;
        double fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());

            op2.setText("");
            fres = oCalculo.Coseno(fop1);

            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnCosenoActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton tangente en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float se crea una variable objeto de la clase CCalculo para poder
     * utilizar sus metodos. Accede al metodo Exp del objeto CCalculo enviandole
     * el valor del campo op1, el valor de op2 es desechado ya que la funcion
     * tangente solo recibe un parametro
     *
     * @param evt
     */

    private void btnTangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTangenteActionPerformed
        float fop1;
        double fres;
        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());

            op2.setText("");
            fres = oCalculo.Tangente(fop1);

            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnTangenteActionPerformed

    /**
     * Este metodo se utiliza al presionar el boton arcoseno en la UI toma el
     * valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float, se crea una variable objeto de la clase CCalculo para poder
     * utilizar sus metodos. Accede al metodo Arcoseno del objeto CCalculo
     * enviandole el valor del campo op1.
     *
     * @param evt
     * @exception Arco, se lanza esta exepcion cuando el valor absoluto del
     * contendio del op1 es mayor a 1.
     */
    private void btnArcosenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcosenoActionPerformed
        // TODO add your handling code here:

        float fop1;
        double fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());

            op2.setText("");

            fres = oCalculo.Arcoseno(fop1);

            res.setText(String.valueOf(fres));
        } catch (Arco e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnArcosenoActionPerformed
    /**
     * Este metodo se utiliza al presionar el boton arcotangente en la UI toma
     * el valor que tiene la casilla op1 y lo transforma a una variable de tipo
     * float, se crea una variable objeto de la clase CCalculo para poder
     * utilizar sus metodos. Accede al metodo Arcotangente del objeto CCalculo
     * enviandole el valor del campo op1.
     *
     * @param evt
     */
    private void btnArcotangenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcotangenteActionPerformed
        // TODO add your handling code here:

        float fop1;
        double fres;

        CCalculo oCalculo;
        oCalculo = new CCalculo();
        try {
            fop1 = Float.parseFloat(op1.getText());

            op2.setText("");

            fres = oCalculo.Arcotangente(fop1);

            res.setText(String.valueOf(fres));
        } catch (java.lang.NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Parece que te faltan operandos");
        }
    }//GEN-LAST:event_btnArcotangenteActionPerformed
    /**
     * Este evento verifica que solo se ingresen caracteres numericos. Si se
     * preciona una tecla no numerica se mostrara un mensaje en pantalla
     * diciendo que solo se pueden presionar numeros
     *
     * @param evt
     */
    private void op1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_op1KeyTyped
        char e = evt.getKeyChar();
        if (Character.isLetter(e)) {
            JOptionPane.showMessageDialog(null, "Solo debes ingresar numeros");
            op1.setText("");
        }
    }//GEN-LAST:event_op1KeyTyped
    /**
     * Este evento verifica que solo se ingresen caracteres numericos. Si se
     * preciona una tecla no numerica se mostrara un mensaje en pantalla
     * diciendo que solo se pueden presionar numeros
     *
     * @param evt
     */
    private void op2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_op2KeyTyped
        char e = evt.getKeyChar();
        if (Character.isLetter(e)) {
            JOptionPane.showMessageDialog(null, "Solo debes ingresar numeros");
            op2.setText("");
        }
    }//GEN-LAST:event_op2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSeno;
    private javax.swing.JButton btnArcocoseno;
    private javax.swing.JButton btnArcoseno;
    private javax.swing.JButton btnArcotangente;
    private javax.swing.JButton btnCoseno;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnExp;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnMiltiplicacion;
    private javax.swing.JButton btnModulo;
    private javax.swing.JButton btnPotencia;
    private javax.swing.JButton btnRaiz;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JButton btnTangente;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField op1;
    private javax.swing.JTextField op2;
    private javax.swing.JTextField res;
    // End of variables declaration//GEN-END:variables
}
